btccom/btcpool

docker/bitcoind/v0.13.0/Dockerfile, docker/bitcoind/v0.13.0/README.md, docker/bitcoind/v0.13.0/bitmain-monitor-bitcoind.sh, docker/bitcoind/v0.13.0/crontab.txt, docker/bitcoind/v0.13.0/logrotate-bitcoind, docker/bitcoind/v0.13.0/run, docker/bitcoind/v0.13.0/sources-aliyun.com.list
Upgrade bitcoind from `v0.12.1` to `v0.13.0`.
WARNING: Miners should **NOT** change `blockmaxsize` to `blockmaxweight` at this time. (v0.13.0)
=> add bitcoind v0.13.0

src/GbtMaker.cc, src/Stratum.cc, src/Stratum.h
- Advertise support for the segwit rule
- Grab default_witness_commitment from gbt
- Insert default_witness_commitment as 2nd txout
TODO:
- Skip insertion if default_witness_commitment doesn't exist
- Verify that merkles are being built without witness data
=> temp segwit hacking

src/Common.h, src/StratumSession.cc, test/TestCommon.cc
This issue is found by @daizisheng
=> improve format diff, O(n^2) -> O(n)

CMakeLists.txt, INSTALL.md, cmake/Modules/FindZookeeperC.cmake, install/install_btcpool.sh, src/Zookeeper.cc, src/Zookeeper.h, src/jobmaker/JobMakerMain.cc, src/jobmaker/jobmaker.cfg
=> auto disaster backup for jobmaker with zookeeper

docker/bitcoind/segwit2x-v1.14.4/Dockerfile, docker/bitcoind/segwit2x-v1.14.4/README.md, docker/bitcoind/segwit2x-v1.14.4/bitmain-monitor-bitcoind.sh, docker/bitcoind/segwit2x-v1.14.4/crontab.txt, docker/bitcoind/segwit2x-v1.14.4/logrotate-bitcoind, docker/bitcoind/segwit2x-v1.14.4/run, docker/bitcoind/segwit2x-v1.14.4/run_testnet3, docker/bitcoind/segwit2x-v1.14.4/sources-aliyun.com.list, docker/bitcoind/v0.14.0/bitmain-monitor-bitcoind.sh, src/jobmaker/jobmaker.cfg
* add Segwit2x bitcoind docker, v1.14.4
* update get external ip address
=> add Segwit2x bitcoind docker

docker/bitcoind/segsignal-v0.14.2/Dockerfile, docker/bitcoind/segsignal-v0.14.2/README.md, docker/bitcoind/segsignal-v0.14.2/bitmain-monitor-bitcoind.sh, docker/bitcoind/segsignal-v0.14.2/crontab.txt, docker/bitcoind/segsignal-v0.14.2/logrotate-bitcoind, docker/bitcoind/segsignal-v0.14.2/run, docker/bitcoind/segsignal-v0.14.2/run_testnet3, docker/bitcoind/segsignal-v0.14.2/sources-aliyun.com.list
using repo: https://github.com/segsignal/bitcoin/tree/segsignal-v0.14.2
* base on bitcoind v0.14.2
* with bip91
=> add segsignal for BIP91

docs/example for modify the config file.md
add a example for run all pool function In one machine.
=> add example for modify the config file

.gitignore, CMakeLists.txt, install/init_folders.sh
Debian/Ubuntu packages can be generated.
=> add `make install` & `make package` support

CMakeLists.txt, src/BlockMaker.cc, src/GbtMaker.cc, src/Stratum.cc, src/StratumServer.cc, src/StratumServer.h, src/StratumSession.cc, src/StratumSession.h
- using POOL__USER_DEFINED_COINBASE_INFO switch, can decide whether or not opening this feature. 
- User can add 10 bytes information to coinbase's tail
=> Enable feature which user could  define coinbaseinfo

test/TestStratum.cc
Add `StratumJobWithRskWork` test to check the correct formation of the coinbase when merge mining.
=> Rsk test rsktag sjob

src/Stratum.cc
remove unused vector:
```vector<uint256> merkleSteps;```
=> remove unused vector

src/bitcoin/StratumBitcoin.h, tools/bitcoin/kafka_repeater/ShareConvertor.hpp, tools/bitcoin/kafka_repeater/shares.hpp, tools/bitcoin/kafka_repeater/utils.hpp
* discard invalid shares.
* move codes about share to `share.hpp`.
=> refactor kafka repeater

src/Stratum.cc, src/Stratum.h, src/StratumServer.cc, src/StratumServer.h, src/StratumSession.cc, src/StratumSession.h, src/sserver/StratumServerMain.cc, src/sserver/sserver.cfg, test/TestStratumSession.cc
Add support Stratum `version-rolling` support specified at http://stratumprotocol.org/
Note: AsicBoost have been [freely available](https://www.asicboost.com/single-post/2018/03/01/opening-asicboost-for-defensive-use/) under the [Blockchain DPL](https://blockchaindpl.org) since March 1, 2018
=> Add Stratum version-rolling extension support

src/Stratum.cc, src/Stratum.h, src/StratumServer.cc, src/StratumServer.h, src/StratumSession.cc, src/StratumSession.h, src/sserver/StratumServerMain.cc, src/sserver/sserver.cfg, test/TestStratumSession.cc
Backport of #57 to legacy branch
=> [backport] Add support for Stratum version-rolling extension

src/StratumClient.cc
Header signal.h needs to be included to have SIGTERM/SIGINT.
=> Fix Linux build

docker/eth-parity/beta-submit_work_detail/README.md, docker/rsk/latest/README.md, docker/rsk/latest/logback.xml, docker/rsk/latest/node.conf, docker/united-bitcoin/v2.3.0.1/Dockerfile, docker/united-bitcoin/v2.3.0.1/README.md, docker/united-bitcoin/v2.3.0.1/logrotate-bitcoind, docker/united-bitcoin/v2.3.0.1/run, docker/united-bitcoin/v2.3.0.1/run_testnet3, docker/united-bitcoin/v2.3.0.1/sources-aliyun.com.list, src/GwMaker.cc, src/GwMaker.h
* a docker for RSK.
* a docker for UB v2.3.0.1 (hardfork 572000).
=> add some dockers

src/decred/DecredUtils.cc, src/decred/DecredUtils.h, src/decred/JobMakerDecred.cc, src/decred/JobMakerDecred.h, src/decred/StatisticsDecred.cc, src/decred/StratumServerDecred.cc, src/decred/StratumServerDecred.h
Block with more voters yields better rewards.
=> DCR: voter relevant optimizations & fixes

.circleci/config.yml, CMakeLists.txt, Dockerfile, README.md, cmake/Modules/GoogleTest.cmake, cmake/Modules/GoogleTestAddTests.cmake
Build & run unit tests for BCH only. Other tests will be added later.
=> Initial CircleCI support

src/decred/StratumServerDecred.cc
DCR sserver tpruvot variant use the whole extra nonce but does not check
whether it matches the extra nonce 1 we set for the miner. Hence the
miner may be able to submit the same result to different sessions.
=> Strict extra nonce 1 usage in DCR submit

src/GwMaker.cc, src/GwMaker.h
=> Fix a GwNotification bug

src/eth/EthConsensus.cc
Support Ethereum Constantinople fork.
=> Ethereum Constantinople fork at block 7080000 on Mainnet

src/Utils.cc, src/Utils.h, src/bitcoin/JobMakerBitcoin.cc, src/bitcoin/JobMakerBitcoin.h, src/gwmaker/GwMakerMain.cc, src/gwmaker/gwmaker.cfg
=> SSL verify peer option for gwmaker

src/ShareLogParser.h, src/ShareLogger.inl, src/Statistics.h, src/Stratum.h, src/beam/StratumBeam.h, src/beam/StratumMinerBeam.cc, src/bitcoin/BitcoinUtils.cc, src/bitcoin/StratumBitcoin.h, src/bitcoin/StratumMinerBitcoin.cc, src/bytom/StratumBytom.h, src/bytom/StratumMinerBytom.cc, src/ckb/StratumCkb.h, src/ckb/StratumMinerCkb.cc, src/decred/StratumDecred.h, src/decred/StratumMinerDecred.cc, src/eth/StratumEth.cc, src/eth/StratumEth.h, src/eth/StratumMinerEth.cc, src/grin/StratumGrin.h, src/grin/StratumMinerGrin.cc, src/sia/StratumMinerSia.cc, src/sia/StratumSia.h
Share codes contains lots of duplications and this PR tries to remove some of them. I also fixes some build errors/warnings while using latest boost & protobuf.
=> Refactor share relevant codes

src/bitcoin/GbtMaker.cc, src/bitcoin/GbtMaker.h
=> fix bch LightMsg bug
